import type { Binding, Keymap, Layer } from '../types/keymap'

function bindingToZmk(b: Binding): string {
  switch (b.type) {
    case 'kp':      return `&kp ${b.key}`
    case 'lt':      return `&lt ${b.layer} ${b.key}`
    case 'mo':      return `&mo ${b.layer}`
    case 'mt':      return `&mt ${b.mod} ${b.key}`
    case 'bt_sel':  return `&bt BT_SEL ${b.profile}`
    case 'bt_clr':  return `&bt BT_CLR`
    case 'out_usb': return `&out OUT_USB`
    case 'out_ble': return `&out OUT_BLE`
    case 'out_tog': return `&out OUT_TOG`
    case 'none':    return `&none`
    case 'trans':   return `&trans`
  }
}

function pad(s: string, width: number): string {
  return s.padEnd(width)
}

function layerBlock(layer: Layer): string {
  const COLS = 10
  const rows: string[][] = []
  for (let r = 0; r < 4; r++) {
    rows.push(layer.bindings.slice(r * COLS, (r + 1) * COLS).map(bindingToZmk))
  }

  // Compute column widths for alignment
  const colWidths = Array(COLS).fill(0) as number[]
  rows.forEach(row => {
    row.forEach((cell, c) => {
      colWidths[c] = Math.max(colWidths[c], cell.length)
    })
  })

  const formattedRows = rows.map(row =>
    row.map((cell, c) => pad(cell, colWidths[c])).join('  ').trimEnd()
  )

  const slug = layer.name.toLowerCase().replace(/[^a-z0-9]/g, '_')
  return [
    `        ${slug}_layer {`,
    `            bindings = <`,
    ...formattedRows.map(r => `                ${r}`),
    `            >;`,
    `        };`,
  ].join('\n')
}

export function generateKeymapFile(keymap: Keymap): string {
  const layerBlocks = keymap.layers.map(layerBlock).join('\n\n')
  return `/*
 * ${keymap.name} ZMK Keymap
 * Generated by Banime40-remap Editor
 * Spacebar variant: ${keymap.spacebarVariant}
 */

#include <behaviors.dtsi>
#include <dt-bindings/zmk/keys.h>
#include <dt-bindings/zmk/bt.h>
#include <dt-bindings/zmk/outputs.h>

/ {
    keymap {
        compatible = "zmk,keymap";

${layerBlocks}
    };
};
`
}
